### ISSUE TITLE
Doesn't work with Kitchen (since 1.23.3)

### ISSUE THREAD

**Issue by philwinder** [inspec/kitchen-inspec#218] opened 2018-12-12 11:33 UTC
It complains about inspec not being installed, but it is, along with kitchen-inspec. It sounds like there's been an API change in the core kitchen code.

```
$ gem install test-kitchen:1.23.5 kitchen-inspec
$ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
...
```

Note that this is the same back to `1.23.3`. `1.23.2` does not throw this error.

.kitchen.yml looks like:
```
verifier:
  name: inspec
  format: documentation
  log_level: debug
```

**Comment by tas50** [comment] 2019-01-23 21:43
I'm not able to reproduce this. I run test-kitchen and inspec via gem and it works fine for me. Do you have additional information on your setup you can give.

**Comment by clintoncwolfe** [comment] 2019-03-01 23:42
As this has been quiet for a while, I'm going to close this; please re-open if additional information is available.

**Closed by clintoncwolfe** 2019-03-01 23:42 UTC
Labels: Aspect: Integration, Type: Bug
